version: "3"

services:

  iris-backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/iris-backend/Dockerfile
    ports:
      - "${IRIS_LISTEN_BINDING}:${IRIS_LISTEN_BINDING}"
    environment:
    - IRIS_CLICKHOUSE_DSN=${IRIS_CLICKHOUSE_DSN}
    - IRIS_CLICKHOUSE_TABLE=${IRIS_CLICKHOUSE_TABLE}
    - IRIS_LISTEN_BINDING=${IRIS_LISTEN_BINDING}
    - IRIS_RECORDER_PATH=${IRIS_RECORDER_PATH}

  zk:
    image: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk:2888:3888;2181

  ch:
    image: yandex/clickhouse-server:latest
    container_name: ch
    volumes:
      - "./docker/clickhouse/config.xml:/etc/clickhouse-server/config.d/common.xml:ro"
      - "./docker/clickhouse/macros.xml:/etc/clickhouse-server/config.d/macros.xml"
      - "./docker/clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml"
      - "./etc/clickhouse/setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9000:9000"
      - "8123:8123"
    expose:
      - "8123"
    tmpfs:
      - /var/lib/clickhouse
    environment:
      CLICKHOUSE_PASSWORD: changeme
    depends_on:
      - zk
