name: Docker image for master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the tagged Docker image
      run: docker build . --file ./docker/iris-backend/Dockerfile --tag irisanalytics/iris-backend:master
    - name: Push the tagged Docker image
      run: docker push irisanalytics/iris-backend:master
